# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HWyW_DiDIMpnd9Qp1Y744ioN1eeTF1W
"""

"""tp1.py

Trabajo Práctico N°1 - Introducción a Python con Menús
Contiene el menú principal y todas las partes A-E con sus ejercicios.
"""

import math
import sys

# -----------------------------
# Parte A - Hola Mundo y Variables
# -----------------------------

def ex_a1_hola_python():
    """Ej 1: Imprime 'Hola Python'"""
    print("\n--- Ejercicio A1: Hola Python ---")
    print("Hola Python")

def ex_a2_variables():
    """Ej 2: Declarar variables con distintos tipos y comentar su uso."""
    print("\n--- Ejercicio A2: Variables y comentarios ---")
    # string: para textos
    nombre = "Maxi"
    # int: números enteros
    edad = 17
    # float: números con decimales
    altura = 1.72
    # bool: verdadero/falso
    es_estudiante = True
    # None: ausencia de valor
    direccion = None

    print(f"nombre (str): {nombre}")
    print(f"edad (int): {edad}")
    print(f"altura (float): {altura}")
    print(f"es_estudiante (bool): {es_estudiante}")
    print(f"direccion (None): {direccion}")

def ex_a3_tipado():
    """Ej 3: Mostrar el tipo de cada variable usando type()"""
    print("\n--- Ejercicio A3: Mostrar tipos con type() ---")
    var_str = "texto"
    var_int = 5
    var_float = 3.14
    var_bool = False
    var_none = None

    variables = [("var_str", var_str), ("var_int", var_int), ("var_float", var_float), ("var_bool", var_bool), ("var_none", var_none)]
    for name, val in variables:
        print(f"{name} = {val}  ->  tipo: {type(val).__name__}")

# -----------------------------
# Parte B - Control de flujo
# -----------------------------

def ex_b4_par_o_impar():
    """Ej 4: Determina si un número es par o impar"""
    print("\n--- Ejercicio B4: Par o Impar ---")
    try:
        n = int(input("Ingresá un número entero: "))
    except ValueError:
        print("Entrada inválida. Debés ingresar un número entero.")
        return

    if n % 2 == 0:
        print(f"{n} es par.")
    else:
        print(f"{n} es impar.")

def ex_b5_clasificar_edad():
    """Ej 5: Clasifica una edad en niño/adolescente/adulto"""
    print("\n--- Ejercicio B5: Clasificar edad ---")
    try:
        edad = int(input("Ingresá la edad (número entero): "))
    except ValueError:
        print("Entrada inválida. Debés ingresar un número entero.")
        return

    if edad < 0:
        print("Edad inválida (negativa).")
    elif edad <= 11:
        print("Clasificación: Niño (0–11)")
    elif edad <= 17:
        print("Clasificación: Adolescente (12–17)")
    else:
        print("Clasificación: Adulto (18+)")

# -----------------------------
# Parte C - Funciones
# -----------------------------

def area_circulo(radio):
    """Calcula el área de un círculo dado su radio."""
    return math.pi * radio * radio

def ex_c6_area_circulo():
    print("\n--- Ejercicio C6: Área de un círculo ---")
    try:
        r = float(input("Ingresá el radio (número): "))
    except ValueError:
        print("Entrada inválida.")
        return
    if r < 0:
        print("El radio no puede ser negativo.")
        return
    a = area_circulo(r)
    print(f"Área del círculo de radio {r} = {a:.4f}")

def suma_lista(numeros):
    """Devuelve la suma de los elementos de la lista 'numeros'."""
    return sum(numeros)

def ex_c7_suma_lista():
    print("\n--- Ejercicio C7: Sumar lista de números ---")
    entrada = input("Ingresá números separados por espacios (ej: 1 2 3.5): ")
    if not entrada.strip():
        print("No ingresaste números.")
        return
    try:
        lista = [float(x) for x in entrada.split()]
    except ValueError:
        print("Entrada inválida. Asegurate de ingresar solo números separados por espacios.")
        return
    total = suma_lista(lista)
    print(f"Lista: {lista}")
    print(f"Suma: {total}")

# -----------------------------
# Parte D - Estructuras de datos
# -----------------------------

def ex_d8_listas():
    print("\n--- Ejercicio D8: Listas y bucle for ---")
    lenguajes = ["Python", "JavaScript", "Java", "C#", "Ruby"]
    print("Lista de lenguajes:")
    for i, lang in enumerate(lenguajes, start=1):
        print(f"{i}. {lang}")

def ex_d9_diccionario_usuario():
    print("\n--- Ejercicio D9: Diccionario - Usuario ---")
    usuario = {
        "nombre": input("Ingresá el nombre del usuario: "),
        "edad": None,
        "email": input("Ingresá el email del usuario: ")
    }
    try:
        usuario["edad"] = int(input("Ingresá la edad del usuario: "))
    except ValueError:
        print("Edad inválida. Se dejará en None.")

    print("\nUsuario:")
    for k, v in usuario.items():
        print(f"{k}: {v}")

# -----------------------------
# Parte E - Clases y POO
# -----------------------------

class Persona:
    """Clase Persona con nombre y edad y método saludar."""
    def __init__(self, nombre: str, edad: int):
        self.nombre = nombre
        self.edad = edad

    def saludar(self):
        print(f"Hola, me llamo {self.nombre} y tengo {self.edad} años.")

def ex_e10_definir_clase():
    print("\n--- Ejercicio E10: Definir clase Persona ---")
    print("La clase Persona está definida en el archivo. Usa la opción E11 para instanciarla y saludar.")

def ex_e11_instanciar_persona():
    print("\n--- Ejercicio E11: Crear instancia de Persona y saludar ---")
    nombre = input("Ingresá el nombre: ")
    try:
        edad = int(input("Ingresá la edad: "))
    except ValueError:
        print("Edad inválida. Usando 0 por defecto.")
        edad = 0
    p = Persona(nombre, edad)
    p.saludar()

# -----------------------------
# Menús
# -----------------------------

def submenu_a():
    while True:
        print("\n--- Parte A — Hola Mundo y Variables ---")
        print("1) Hola Python")
        print("2) Declarar variables")
        print("3) Mostrar tipo de variables")
        print("b) Volver al menú principal")
        opcion = input("Elegí una opción: ").strip().lower()
        if opcion == '1':
            ex_a1_hola_python()
        elif opcion == '2':
            ex_a2_variables()
        elif opcion == '3':
            ex_a3_tipado()
        elif opcion == 'b':
            break
        else:
            print("Opción inválida.")

def submenu_b():
    while True:
        print("\n--- Parte B — Control de Flujo ---")
        print("1) Par o impar")
        print("2) Clasificar edad")
        print("b) Volver al menú principal")
        opcion = input("Elegí una opción: ").strip().lower()
        if opcion == '1':
            ex_b4_par_o_impar()
        elif opcion == '2':
            ex_b5_clasificar_edad()
        elif opcion == 'b':
            break
        else:
            print("Opción inválida.")

def submenu_c():
    while True:
        print("\n--- Parte C — Funciones ---")
        print("1) Área de un círculo")
        print("2) Suma de una lista de números")
        print("b) Volver al menú principal")
        opcion = input("Elegí una opción: ").strip().lower()
        if opcion == '1':
            ex_c6_area_circulo()
        elif opcion == '2':
            ex_c7_suma_lista()
        elif opcion == 'b':
            break
        else:
            print("Opción inválida.")

def submenu_d():
    while True:
        print("\n--- Parte D — Estructuras de Datos ---")
        print("1) Listas: lenguajes de programación")
        print("2) Diccionario: usuario")
        print("b) Volver al menú principal")
        opcion = input("Elegí una opción: ").strip().lower()
        if opcion == '1':
            ex_d8_listas()
        elif opcion == '2':
            ex_d9_diccionario_usuario()
        elif opcion == 'b':
            break
        else:
            print("Opción inválida.")

def submenu_e():
    while True:
        print("\n--- Parte E — Clases y POO ---")
        print("1) Definir clase Persona")
        print("2) Crear instancia y saludar")
        print("b) Volver al menú principal")
        opcion = input("Elegí una opción: ").strip().lower()
        if opcion == '1':
            ex_e10_definir_clase()
        elif opcion == '2':
            ex_e11_instanciar_persona()
        elif opcion == 'b':
            break
        else:
            print("Opción inválida.")

def main_menu():
    while True:
        print("\n=== Menú Principal — TP1 (Python) ===")
        print("A) Parte A — Hola Mundo y Variables")
        print("B) Parte B — Control de Flujo")
        print("C) Parte C — Funciones")
        print("D) Parte D — Estructuras de Datos")
        print("E) Parte E — Clases y POO")
        print("S) Salir")
        opcion = input("Elegí una opción: ").strip().lower()
        if opcion == 'a':
            submenu_a()
        elif opcion == 'b':
            submenu_b()
        elif opcion == 'c':
            submenu_c()
        elif opcion == 'd':
            submenu_d()
        elif opcion == 'e':
            submenu_e()
        elif opcion == 's':
            print("Saliendo. ¡Hasta luego!")
            break
        else:
            print("Opción inválida. Elegí A, B, C, D, E o S.")

if __name__ == '__main__':
    try:
        main_menu()
    except KeyboardInterrupt:
        print("\nInterrumpido por el usuario. Saliendo...")
        sys.exit(0)